name: Build

on:
    release:
        types: [published]

jobs:
    build:
        strategy:
            matrix:
                os: [
                  ubuntu-20.04, ubuntu-22.04, ubuntu-24.04,
                  macos-13, macos-14, macos-15,
                  windows-2019, windows-2022, windows-2025
                ]
                python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
            fail-fast: false
            # max-parallel: 1
        
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup Python v${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            # - name: Install Rust Toolchain
            #   uses: actions-rs/toolchain@v1
            #   with:
            #     toolchain: stable
            #     profile: minimal
            #     override: true
            
            # - name: Install Maturin
            #   run: |
            #     python -m pip install --upgrade pip
            #     pip install maturin build
            
            - name: Build Artifact
              run: |
                chmod a+x ./setup.sh
                ./setup.sh
                pip install -U build wheel 'setuptools>=75.0'
                python build.py bdist_wheel --plat-name=$(python -c "import distutils.util; print(distutils.util.get_platform())")
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                path: dist/*.whl
                name: artifact-${{ matrix.python-version }}-${{ matrix.os }}
    
    merge:
        runs-on: ubuntu-latest

        needs: build
        steps:
            - name: Merge Artifacts
              uses: actions/upload-artifact/merge@v4
              with:
                name: Builds
                pattern: artifact-*